### ISSUE TITLE
Geolocation.watchposition stops working when app in background or device locked

### ISSUE THREAD

**Issue by Bonissauro** [react-native-community/react-native-geolocation#55]
Hello!

As almost everybody here, I'm trying to capture device`s geolocation intending to track my company cars when delivering.

For that, I'm using Geolocation.watchposition and it's working very well on IOS and most part of android devices I've been testing. However, and only on Samsung devices with Knox Library, the location services stop working when I lock ou minimize my app. When it comes to foreground, everything gets working again, but I loose every coordinate I got when locked ou in background.

Would someone know whats the catch?

10x in advance for any help

**Comment by matt-oakes** [comment]
:wave: This library (and most other location ones) are designed to be used when the app is in the foreground. This is because running code in the background is more complicated and would lead to a much more complicated library. Most app do not need to track location in the background, so it's usually not worth supporting.

As your use case does require background location tracking, your best bet is to use this React Native library, which is specifically designed to support it:

https://github.com/transistorsoft/react-native-background-geolocation

**Comment by ansarikhurshid786** [comment]
https://github.com/transistorsoft/react-native-background-geolocation library is paid for android.

**Comment by SyedTayyabUlMazhar** [comment]
To make background location work:

### iOS: 
In order to enable geolocation in the background, you need to include the 'NSLocationAlwaysUsageDescription' key in Info.plist and add location as a background mode in the 'Capabilities' tab in Xcode.

## Android 10 and above( API >= 29):
You need to add `<uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" />` and also check & request permission at runtime.

**Comment by YuriLima23** [comment]
in 2024 where existing many applications the geolocation like uber, 99, in-drive and others , i think is essentials processing in background

**Comment by BadirkhanovRovshanITStep** [comment]
I hope it will help: https://github.com/michalchudziak/react-native-geolocation/blob/master/example/src/configs/BackgroundLocationUpdates.tsx#L28
